### PR TITLE
Add new signal "href" for full url

### LINKED ISSUE #4: A Signal for the entire Location
At the moment, elm-history offers signals for the `location.path` and `location.hash`. However, people are sometimes interested in other parts of the location -- say, for instance, the query string.

In fact, there is a pull request open elsewhere to add this: https://github.com/TheSeamau5/elm-history/pull/5

Now, what I would propose to do instead is create a `Signal Location`, where the `Location` is a record that has _all_ the parts of the location object. That way, people can just pick out the parts they want. (In fact, a signal of just hashes, for instance, would just be a `Signal.map` of the `Signal Location`).

So, I'd propose to go ahead and do that, but I'll wait a few days to see if anyone has any comments.

### PR DESCRIPTION
**Pull request by liamcurry**
This PR adds a new signal `href`, which is an alias for `window.location.href` and can be used to get the full URL with query string parameters. Fixes #4.

### CODE REVIEW

**Comment by sporto** [comment]
+1 for merging this.

**Comment by liamcurry** [comment]
@rgrempel @lukewestby not sure if you're the right people to ask but is there any word on getting this merged to master? I'm happy to make changes if needed.

**Comment by rgrempel** [comment]
My apologies for the delay in looking at this before now. I've given it a quick look, and at first glance it looks good to me. I'll take a closer look at it tomorrow.

**Comment by rgrempel** [comment]
Thanks -- this really is the best approach, I think, since the location.href also gives you the query string, which I don't think we were providing before. Of course, you'd have to parse it, but that's a separate issue.

**Comment by rgrempel** [comment]
I'll do a new release momentarily ...

**Comment by rgrempel** [comment]
Version 1.1 released ... thanks!

**Comment by liamcurry** [comment]
Thanks for the quick response @rgrempel !

**Pull request merged**
