### PR TITLE
Add example integration with StartApp effects

### PR DESCRIPTION
**Pull request by naufraghi**
My fist Elm contribution, comments are welcome.

### CODE REVIEW

**Comment by rgrempel** [comment]
Thanks for contributing this!

One small simplification would be this:

```
diff --git a/examples/effects/HistoryEffects.elm b/examples/effects/HistoryEffects.elm
index 637dad9..029f190 100644
--- a/examples/effects/HistoryEffects.elm
+++ b/examples/effects/HistoryEffects.elm
@@ -39,7 +39,8 @@ update action model =

 setHistory : String -> Effects Action
 setHistory url =
-  History.setPath ("#" ++ url) `Task.andThen` (always (Task.succeed url))
+  History.setPath ("#" ++ url)
+  |> Task.map (always url)
   |> Task.toMaybe
   |> Task.map SettedHistory
   |> Effects.task
```

That is, if you're going to call `Task.succeed` anyway, then you could just `Task.map` instead of `Task.andThen` -- you don't really need `andThen` if all you want to do is change the result (without "really" executing another Task).

The other issue I see is that if you hit the "back" button in the browser, there seems to have been an extra history entry generated ... for instance, if I'm on "a", and I click on "link to #b", then I have to hit the browser's back button **twice** in order to get back to "a".

Is that something you'd like to try to fix? It's a useful example even with that flaw, but it might be nice to figure out how to fix it.

**Comment by naufraghi** [comment]
You are right, I didn't noticed it. I've an half fix I'll submit.

**Comment by naufraghi** [comment]
I spitted up a `Route` action that do not updates the history and a `FollowHash` action that has the same effect as the `href` link.

**Comment by rgrempel** [comment]
Thanks, that looks good.

This is a useful example, so I'll merge it -- if any problems are apparent on further examination, we can always fix them.

**Pull request merged**
